[workspace]
members = ["packages/xiv-launcher-auth"]

[package]
name = "xiv-launcher-rs"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
name = "xiv_launcher_rs_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
xiv-launcher-auth = { path = "packages/xiv-launcher-auth" }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["rustls-tls"], default-features = false }
dirs = "5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
rpassword = "7"

[[example]]
name = "sdo_launch"
path = "examples/sdo_launch.rs"
required-features = ["xiv-launcher-auth/sdo"]

